<? $this->headTitle('Kokoelmalinjat'); $this->content()->setHeading('Satakirjastojen kokoelmalinjat'); ?>

<div class="row">
    
    <div class="col-sm-3 sidebar">
        <div class="content-navigation-menu">
        </div>
    </div>

	<div class="col-md-9 col-xs-12">
	    <div id="periaatteet" class="content-section">
	    <h2>Periaatteet</h2>
        <p>Satakirjastot on kaikista Satakunnan kaupungin- ja kunnankirjastoista sekä yksityisestä Skibban-kirjastosta 
			muodostuva kirjastokimppa, jonka toimintaa ohjaavat laki yleisistä kirjastoista (1492/2016) ja yhteisesti sovitut 
			säännöt. Palveluiden järjestämisessä lähtökohtina ovat maksuttomuus, yhteisöllisyys, moniarvoisuus ja 
			kulttuurinen moninaisuus. Lain mukaan yleisen kirjaston tehtävänä on muun muassa ylläpitää monipuolista ja 
			uudistuvaa kokoelmaa. Satakirjastot tarjoaa yhteiskäyttöisen kokoelman avulla jokaiselle asiakkaalle 
			yhdenvertaisen mahdollisuuden sivistykseen ja elämyksiin ja edistää tiedon saamista, lukuharrastusta, elinikäistä 
			oppimista ja aktiivista kansalaisuutta.</p>
	    </div>
		<div id="kokoelmat" class="content-section">
		<h2>Kokoelmat</h2>

		<p>Yhteiskäyttöinen kokoelma, aineistojen liikkuvuus ja valtakunnallinen yhteistyö takaavat, että kaikkialla Satakunnassa 
			asiakkaat saavat haluamiaan aineistoja nopeasti ja vaivattomasti käsiinsä. Varaaminen kimpan kirjastoista on asiakkaille 
			maksutonta. Varauksen voi noutaa mistä tahansa kimppaan kuuluvasta kirjastosta ja lainan voi palauttaa mihin tahansa 
			niistä.</p>
	    
		<p>Satakirjastojen fyysisten kokoelmien yhteenlaskettu määrä on noin 1,55 miljoonaa nidettä (2025). Kokoelmat sisältävät 
			painettujen kirjojen lisäksi mm. lehtiä, elokuvia, musiikkia ja pelejä. Monissa kirjastoissa on myös erikoisaineistoa kuten 
			kausikortteja ja liikuntavälineitä. </p>
		<p>Satakirjastojen kirjastot ylläpitävät omia kotiseutukokoelmiaan, joihin talletetaan omaa paikkakuntaa koskevaa kirjallisuutta, 
			pienpainatteita, musiikkia, elokuvia jne.</p>
        <p>Aineiston löytämistä, selaamista ja varaamista varten Satakirjastoilla on helppokäyttöinen ja monipuolinen 
			<a href="https://satakirjastot.finna.fi">verkkokirjasto</a>. 
			Aineistoja esitellään kirjastoissa monin tavoin mm. näyttelyiden, tapahtumien, opastuksen ja vinkkauksen avulla.</p>
		<p>Satakirjastojen asiakkaat saavat käyttöönsä myös erilaisia e-aineistoja: elokuvia, kieli- ja musiikkikursseja sekä 
			sanomalehtiä. Näiden lisäksi jokaiselle satakuntalaiselle tarjotaan pääsy valtakunnalliseen E-kirjastoon. 
			<a href="https://www.kansalliskirjasto.fi/fi/e-kirjasto" target="_blank">E-kirjasto</a> on 
			kuntien yhteinen palvelu, josta voi lainata e-kirjoja, e-äänikirjoja ja e-lehtiä.</p>
		</div>
		
		
        <div id="hankinta" class="content-section">
            <h2>Hankinta</h2>
            <p>Satakirjastoihin kuuluvat kirjastot kehittävät omatoimisesti kokoelmiaan, kuitenkin maakunnallista kokoelmaa silmällä 
				pitäen. Tässä työssä otetaan huomioon alueellinen ja paikallinen kulttuuri sekä asiakkaiden tasa-arvoinen kohtelu. Aineistoa 
				hankitaan pääosin kilpailutuksen perusteella valituista hankintapaikoista. Ensisijaisia valintaperiaatteita ovat aineiston 
				kysyntä, ajankohtaisuus sekä laatu. Kirjastoissa pyritään välttämään aineistoa, joka loukkaa ihmisoikeuksia tai 
				vähemmistöjä. Tavoitteena on moniarvoinen, uudistuva ja ajallisesti syvä aineistokokoelma.</p>
            
            <p>Asiakkaiden hankintaehdotukset ovat kirjastoissa tervetulleita. Niitä otetaan mieluiten vastaan
				kirjallisesti <a href="https://satakirjastot.finna.fi/Feedback/Form/AcquisitionRequestAPI" target="_blank">
    			hankintaehdotuslomakkeen</a> kautta. Hankintaehdotukset toteutetaan, mikäli ne ovat valintaperiaatteiden mukaisia ja 
				muuten toteutettavissa. Kirjasto voi esimerkiksi hankkia vain sellaisia elokuvia, joille on myönnetty lainausoikeus. Joskus on 
				tarkoituksenmukaista tilata toivottu aineisto asiakkaan käyttöön kaukolainana tai siirtokokoelmana.</p>    
        </div>
		
		<div id="lahjoitukset" class="content-section">
		<h2>Lahjoitukset</h2>
		<p>Lahjoituksien vastaanottamisesta päättää kukin kirjasto itsenäisesti. Lahjoitus siirtyy aina kirjaston omaisuudeksi. Se voi 
			päätyä kierrätykseen tai kirjaston poistomyyntiin. Lahjoituksia voidaan myös tarjota muille kirjastoille.</p>
		</div>

		<div id="varastointi" class="content-section">
		<h2>Varastot</h2>
		<p>Kirjastojen varastoissa säilytetään vähemmän lainattua, vanhempaa tai huonohkossa kunnossa olevaa aineistoa, jolla on 
			kuitenkin mahdollisesti kysyntää. Varastokokoelmat ovat asiakkaiden käytettävissä.</p>
		</div>
		
		<div id="poistot" class="content-section">
		    <h2>Poistot</h2>
		    <p>Käytön arvioiminen ja kokoelman karsiminen on jatkuva osa kokoelmanhoitoa. Poistoperusteita ovat aineiston alhainen 
				käyttöaste, huono kunto sekä tietojen vanhentuminen. Poistettua aineistoa lahjoitetaan, kierrätetään ja myydään. Aineistoa 
				ei poisteta eikä myydä toivomusten perusteella.</p>
		</div>
  </div>
</div>
  
