<? $this->headTitle('Kokoelmalinjaukset'); $this->content()->setHeading('Satakirjastojen kokoelmalinjaukset'); ?>

<div class="row">
    
    <div class="col-sm-3 sidebar">
        <div class="content-navigation-menu">
        </div>

    </div>

	<div class="col-md-9 col-xs-12">
	    <div id="periaatteet" class="content-section">
	    <h2>Periaatteet</h2>
        <p>Satakirjastot on Satakunnan kaupungin- ja kunnankirjastojen yhteinen palvelujärjestelmä, jonka
toimintaa ohjaa laki yleisistä kirjastoista (1492/2016). Palveluiden järjestämisessä lähtökohtina
ovat yhteisöllisyys, moniarvoisuus ja kulttuurinen moninaisuus. Lain mukaan yleisen kirjaston
tehtävänä on muun muassa ylläpitää monipuolista ja uudistuvaa kokoelmaa. Satakirjastot
tarjoaa yhteiskäyttöisen kokoelman avulla jokaiselle asiakkaalle yhdenvertaisen
mahdollisuuden sivistykseen, tiedon saamiseen, lukuharrastukseen, elinikäiseen oppimiseen
sekä aktiiviseen kansalaisuuteen.</p>
	    </div>
		<div id="kokoelmat" class="content-section">
		<h2>Kokoelmat</h2>

		<p>Yhteiskäyttöinen kokoelma, aineistojen liikkuvuus ja valtakunnallinen yhteistyö takaavat, että
kaikkialla Satakunnassa asiakkaat saavat haluamiaan aineistoja nopeasti ja vaivattomasti
käsiinsä. Satakirjastot tarjoaa asiakkailleen ilmaiset varaukset kaikista maakunnan yleisistä
kirjastoista. Varauksen voi noutaa mistä tahansa kimppaan kuuluvasta kirjastosta ja lainan voi
palauttaa mihin tahansa niistä.</p>
	    
		<p>Satakirjastojen kokoelmien yhteenlaskettu määrä on noin 1,7 miljoonaa nidettä. Kokoelmat
sisältävät painettujen kirjojen lisäksi muun muassa äänikirjoja, lehtiä, elokuvia, musiikkia,
pelejä ja yhteisiä verkkoaineistoja. Joissakin kirjastoissa on myös erikoisaineistoa kuten
kausikortteja ja liikuntavälineitä.</p>
		<p>Jokainen Satakirjastojen kirjasto ylläpitää omaa kotiseutukokoelmaansa, johon talletetaan omaa
paikkakuntaa koskevaa kirjallisuutta, pienpainatteita, musiikkia ja elokuvia.</p>
        <p>Aineiston löytämistä, selaamista ja varaamista varten Satakirjastot tarjoaa helppokäyttöisen ja
monipuolisen <a href="https://satakirjastot.finna.fi">verkkokirjaston</a>. Aineistoja esitellään kirjastoissa monin tavoin
näyttelyiden, tapahtumien, opastuksen ja vinkkauksen avulla.</p>
		</div>
		
		
        <div id="hankinta" class="content-section">
            <h2>Hankinta</h2>
            <p>Satakirjastoihin kuuluvat kirjastot kehittävät omatoimisesti kokoelmiaan, kuitenkin
maakunnallista kokoelmaa silmällä pitäen. Tässä työssä otetaan huomioon alueellinen ja
paikallinen kulttuuri sekä asiakkaiden tasa-arvoinen kohtelu. Aineistoa hankitaan 
pääsääntöisesti kilpailutuksen perusteella valituista hankintapaikoista. Ensisijaisia
valintaperiaatteita ovat aineiston kysyntä, ajankohtaisuus sekä laatu. Kirjastoissa pyritään
välttämään aineistoa, joka loukkaa ihmisoikeuksia tai vähemmistöjä. Tavoitteena on
moniarvoinen, uudistuva ja ajallisesti syvä aineistokokoelma.
</p>
            
            <p>Asiakkaiden hankintaehdotukset ovat kirjastoissa tervetulleita. Niitä otetaan mieluiten vastaan
kirjallisesti <a href="https://satakirjastot.finna.fi/Feedback/Form/AcquisitionRequestAPI" target="_blank">
    hankintaehdotuslomakkeen</a> kautta. Hankintaehdotukset toteutetaan, mikäli
ne ovat valintaperiaatteiden mukaisia ja muuten toteutettavissa. Esimerkiksi
elokuvatallenteiden osalta kirjasto voi hankkia vain sellaisia tuotteita, joille on myönnetty
lainausoikeus. Joskus on tarkoituksenmukaista tilata toivottu aineisto asiakkaan käyttöön
muualta (kaukolainat, siirtokokoelmat).</p>
            
        </div>
		
		<div id="lahjoitukset" class="content-section">
		<h2>Lahjoitukset</h2>
		<p>Pääsääntöisesti lahjoituksia ei oteta vastaan, mutta kukin kirjasto päättää asiasta itsenäisesti.
Mikäli kirjasto tekee päätöksen vastaanottamisesta, lahjoitus siirtyy kirjaston omaisuudeksi.
Osa lahjoituksista voi päätyä kierrätykseen tai kirjaston poistomyyntiin. Lahjoituksia voidaan
myös tarjota muille kirjastoille.</p>
		
		</div>

		<div id="varastointi" class="content-section">
		<h2>Varastointi</h2>
		<p>Kirjastoissa varastoidaan vähemmän lainattua, vanhempaa tai huonohkossa kunnossa olevaa
aineistoa, jolla on kuitenkin mahdollisesti kysyntää. Varastoinnissa otetaan huomioon
maakunnallinen kokoelma. Varastokokoelmissa säilytetään sekä paikallisesti että kulttuurisesti
merkittävää aineistoa.</p>
		</div>
		
		<div id="poistot" class="content-section">
		    <h2>Poistot</h2>
		    <p>Käytön arvioiminen ja kokoelman karsiminen on jatkuva osa kokoelmanhoitoa.
Poistoperusteita ovat aineiston alhainen käyttöaste, huono kunto sekä tietojen vanhentuminen.
Poistettua aineistoa lahjoitetaan, kierrätetään ja myydään. Aineistoa ei myydä toivomusten
perusteella.</p>
		</div>


	
	
  </div>
  
