<? $this->headTitle('Kokoelmastrategia'); $this->content()->setHeading('Satakirjastojen kokoelmastrategia'); ?>

<div class="row">
    
    <div class="col-sm-3 sidebar">
        <div class="content-navigation-menu">
        </div>
    </div>

	<div class="col-md-9 col-xs-12">
	    <div id="missio" class="content-section">
	    <h2>Millaisen kokoelman haluamme tarjota</h2>
        <p>Satakirjastot tarjoaa käyttäjilleen uudistuvan, mutta ajallisesti syvän kokoelman. 
			Sisällöt ovat monipuolisia ja moniäänisiä. Kokoelma tukee oppimista ja sivistystä sekä viihdyttää.</p>
	    </div>
	    
		<div id="visio" class="content-section">
		<h2>Millaiset kokoelmat meillä on vuonna 2030</h2>

		<p>Kirjastot hoitavat ja kehittävät paikallista kokoelmaa yhdessä. Asiakkaita palvelee ajantasainen, 
			kiinnostava ja houkutteleva kokoelma. Kokoelmatyössä huomioidaan kaikille saavutettavat 
			aineistomuodot ja uudenlaiset sisällöt sekä ekologisuus.</p>
	    
		<p>Kansalliset yhteiskokoelmat toimivat osana Satakirjastojen kokoelmaa:</p>
		<ul class="list-bullets">
		    <li>E-aineistot ovat kiinteä ja näkyvä osa Satakirjastojen kokoelmaa ja asiakkaiden aktiivisessa käytössä 
             </li>
		    <li>Monikielisen kirjaston valikoimaa hyödynnetään aiempaa enemmän
            </li>
		</ul>
		</div>
		
		
        <div id="toteutus" class="content-section">
            <h2>Miten saavutamme tavoitteen</h2>
            <ul class="list-bullets">
                <li>Takaamme laadukkaan kokoelman Satakirjastoissa yhdessä sovituilla kirjastoaineiston 
       				valinnan, varastoinnin ja poiston periaatteilla 
					(<a href="<?=$this->url('content-page', ['page' => 'kokoelma'])?>">ks. kokoelmalinjat</a>)</li>
                <li>Kehitämme kaikissa Satakirjastoissa omatoimisesti kokoelmiamme, 
       				kuitenkin yhteistä kokoelmaa silmällä pitäen</li>
                <li>Varmistamme aineiston saatavuuden riittävällä hankinnalla sekä 
       				toimivilla kirjastojen välisillä kuljetuksilla</li>
                <li>Huolehdimme siitä, että kouluyhteistyötä tukevaa aineistoa on riittävästi ja monipuolisesti saatavilla</li>
				<li>Huomioimme ekologisuuden kaikissa hankinnan ja poiston prosesseissa</li>
				<li>Tarjoamme E-kirjaston valikoiman myös verkkokirjastosta</li>
				<li>Tiivistämme yhteistyötä Monikielisen kirjaston kanssa</li>
            </ul>  
        </div>
		
		<div id="arvot" class="content-section">
		<h2>Mihin arvoihin ja periaatteisiin kokoelmapolitiikkamme perustuu</h2>
		<ul class="list-bullets">
                <li>Kokoelma palvelee eri-ikäisiä ja -taustaisia käyttäjiä sekä erilaisia kieli-, kulttuuri- ja katsomusryhmiä</li>
                <li>Kokoelma tukee avointa tiedonsaantia, moniarvoisuutta ja kriittistä ajattelua</li>
                <li>Kokoelma tarjoaa sisältöjä eri muodoissa, jotta ne ovat mahdollisimman monen saavutettavissa</li>
				<li>Kokoelmatyö perustuu asiantuntijuuteen sekä sisällön laatuun, ajantasaisuuteen ja tiedolliseen luotettavuuteen</li>
				<li>Kokoelmatyö toteutuu ekologisesti, taloudellisesti ja pitkäjänteisesti</li>
				<li>Kokoelmatyötä ohjaavat asiakkaiden tarpeet, kiinnostuksen kohteet ja palaute</li>
            </ul>
		
		</div>
	</div>
</div>
  
