<? $this->headTitle('Kokoelmastrategia'); $this->content()->setHeading('Satakirjastojen kokoelmastrategia'); ?>

<div class="row">
    
    <div class="col-sm-3 sidebar">
        <div class="content-navigation-menu">
        </div>

    </div>

	<div class="col-md-9 col-xs-12">
	    <div id="missio" class="content-section">
	    <h2>Mitä saat Satakirjastoista?</h2>
        <p>Satakirjastot tarjoaa käyttäjilleen uudistuvan, mutta ajallisesti syvän kokoelman. 
        Sisällöt ovat monipuolisia ja moniäänisiä. Kokoelma tukee oppimista ja sivistystä sekä viihdyttää. </p>
	    </div>
	    
		<div id="visio" class="content-section">
		<h2>Millaiset kokoelmat meillä on vuonna 2030? </h2>

		<p>Kirjastot hoitavat ja kehittävät paikallista kokoelmaa yhdessä. Asiakkaita palvelee ajantasainen, 
		kiinnostava ja houkutteleva kokoelma.  </p>
	    
		<p>Kansalliset yhteiskokoelmat toimivat osana Satakirjastojen kokoelmaa: </p>
		<ul class="list-bullets">
		    <li>Satakirjastojen asiakkaat käyttävät yleisten kirjastojen yhteistä e-kirjastokokoelmaa <br>
		    <span style="font-size: smaller;">E-kirjastokokoelma tarjoaa laajan valikoiman e-kirjoja ja e-äänikirjoja, mutta siihen 
		    sisältyy myös kattava lehti- ja elokuvakokoelma</span>
             </li>
		    <li>Varastokirjasto laajentaa Satakirjastojen paikallista kokoelmaa <br>
		    <span style="font-size: smaller;">Voit varata vanhempaa aineistoa suoraan valtakunnallisesta Varastokirjastosta Kuopiosta, 
		    jos se puuttuu Satakirjastojen kokoelmasta</span>
            </li>
		</ul>
		<p>Satakirjastot palvelevat kaikkia asiakasryhmiä tarjoamalla vaihtelevaa valikoimaa eri kielillä. Huomioimme kokoelmassa kaikille 
		saavutettavat aineistomuodot ja uudenlaiset sisällöt. </p>
		</div>
		
		
        <div id="toteutus" class="content-section">
            <h2>Miten saavutamme tavoitteen? </h2>
            <ul class="list-bullets">
                <li>Noudatamme yhteisiä <a href="<?=$this->url('content-page', ['page' => 'kokoelma'])?>">kokoelmalinjoja</a></li>
                <li>Satakirjastoilla on yhdessä sovitut kirjastoaineiston valinnan, varastoinnin ja poiston periaatteet, 
                joilla takaamme laadukkaan kokoelman</li>
                <li>Aineiston saatavuus varmistetaan riittävällä hankinnalla sekä toimivilla kirjastojen 
                välisillä kuljetuksilla. Kaikki kirjastot vastaavat osaltaan aineiston saatavuudesta</li>
                <li>Satakirjastoihin kuuluvat kirjastot kehittävät omatoimisesti kokoelmiaan, kuitenkin yhteistä kokoelmaa silmällä pitäen</li>
            </ul>
            
        </div>
		
		<div id="arvot" class="content-section">
		<h2>Mihin arvoihin toimintamme perustuu? </h2>
		<ul class="list-bullets">
                <li>Kohtelemme asiakkaita tasa-arvoisesti </li>
                <li>Kokoelmassa on edustettuna laajasti ja ennakkoluulottomasti eri näkökulmia. Pyrimme kuitenkin välttämään aineistoa, 
                joka loukkaa ihmisoikeuksia ja vähemmistöjä</li>
                <li>Yhteinen kokoelma palvelee asiakkaita kaikissa Satakunnan kuntien kirjastoissa</li>
            </ul>
		
		</div>
  </div>
  
